version: 2
jobs:
  build:
    docker:
      - image: crops/poky:ubuntu-18.10
        # entrypoint: /usr/bin/dumb-init -- /usr/bin/poky-entry.py
        command: --workdir /home/pokyuser
        # user: pokyuser
    steps:
      - checkout
      - run:
          name: Checkout dependencies
          command: git submodule update
      - restore_cache:
          keys:
            - cache-v1-{{ .Branch }}-{{ .Revision }}
            - cache-v1-{{ .Branch }}-
            - cache-v1-
      - run:
          name: Build
          no_output_timeout: 1h
          command: |
            cd poky
            source oe-init-build-env ../build
            bitbake --quiet core-image-base
      - store_artifacts:
          name: Store mender image
          path: build/tmp/deploy/images/raspberrypi0-wifi/core-image-base-raspberrypi0-wifi.mender
          destination: candy.mender
      - store_artifacts:
          name: Store sd card image
          path: build/tmp/deploy/images/raspberrypi0-wifi/core-image-base-raspberrypi0-wifi.sdimg
          destination: candy.rpi-sdimg
      - save_cache:
          key: cache-v1-{{ .Branch }}-{{ .Revision }}
          when: always
          paths:
            - build/cache
            - build/downloads
            - build/sstate-cache
workflows:
  version: 2
  workflow:
    jobs:
      - build
