version: 2.1
jobs:
  build:
    docker:
      - image: crops/poky:ubuntu-18.10
    steps:
      - checkout
      - run:
          name: Hello
          command: 'pwd && ls -al && cd /workdir && ls -al && cd poky && ls -al'
